package com.hendrix.mirror.resources.timeline
{
  public class MenuItem
  {
    /**
     * REPLY - Initiate a reply to the timeline item using the voice recording UI. The creator attribute must be set in the timeline item for this menu to be available. 
     */
    static public const REPLY:String = "REPLY";
    /**
     * REPLY_ALL - Same behavior as REPLY. The original timeline item's recipients will be added to the reply item. 
     */
    static public const REPLY_ALL:String = "REPLY_ALL";
    /**
     * DELETE - Delete the timeline item.  
     */
    static public const DELETE :String = "DELETE";
    /**
     * SHARE - Share the timeline item with the available contacts.
     */
    static public const SHARE:String = "SHARE";
    /**
     * READ_ALOUD - Read the timeline item's speakableText aloud; if this field is not set, read the text field; if none of those fields are set, this menu item is ignored. 
     */
    static public const READ_ALOUD :String = "READ_ALOUD";
    /**
     * GET_MEDIA_INPUT - Allow users to provide media payloads to Glassware from a menu item (currently, only transcribed text from voice input is supported). Subscribe to notifications when users invoke this menu item to receive the timeline item ID. Retrieve the media from the timeline item in the payload property.
     */
    static public const GET_MEDIA_INPUT:String = "GET_MEDIA_INPUT";
    /**
     * VOICE_CALL - Initiate a phone call using the timeline item's creator.phoneNumber attribute as recipient. 
     */
    static public const VOICE_CALL :String = "VOICE_CALL";
    /**
     * NAVIGATE - Navigate to the timeline item's location. 
     */
    static public const NAVIGATE:String = "NAVIGATE";
    /**
     * TOGGLE_PINNED - Toggle the isPinned state of the timeline item. 
     */
    static public const TOGGLE_PINNED:String = "TOGGLE_PINNED";
    /**
     * OPEN_URI - Open the payload of the menu item in the browser.
     */
    static public const OPEN_URI:String = "OPEN_URI";
    /**
     * PLAY_VIDEO - Open the payload of the menu item in the Glass video player. 
     */
    static public const PLAY_VIDEO:String = "PLAY_VIDEO";
    /**
     * SEND_MESSAGE - Initiate sending a message to the timeline item's creator:<li>If the creator.phoneNumber is set and Glass is connected to an Android phone, the message is an SMS.<li>Otherwise, if the creator.email is set, the message is an email.
     */
    static public const SEND_MESSAGE:String = "SEND_MESSAGE";
    /**
     * CUSTOM - Custom action set by the service. When the user selects this menuItem, the API triggers a notification to your callbackUrl with the userActions.type set to CUSTOM and the userActions.payload set to the ID of this menu item. This is the default value.
     */
    static public const CUSTOM:String = "CUSTOM";
    
    /**
     * The ID for this menu item. This is generated by the application and is treated as an opaque token.
     */ 
    public var id:                  String                  = null;
    
    
    /**
     * Controls the behavior when the user picks the menu option. Allowed values are: <br> CUSTOM - Custom action set by the service. When the user selects this menuItem, the API triggers a notification to your callbackUrl with the userActions.type set to CUSTOM and the userActions.payload set to the ID of this menu item. This is the default value.Built-in actions:<li>REPLY - Initiate a reply to the timeline item using the voice recording UI. The creator attribute must be set in the timeline item for this menu to be available. <li>REPLY_ALL - Same behavior as REPLY. The original timeline item's recipients will be added to the reply item.<li>DELETE - Delete the timeline item.<li>SHARE - Share the timeline item with the available contacts.<li>READ_ALOUD - Read the timeline item's speakableText aloud; if this field is not set, read the text field; if none of those fields are set, this menu item is ignored.<li>GET_MEDIA_INPUT - Allow users to provide media payloads to Glassware from a menu item (currently, only transcribed text from voice input is supported). Subscribe to notifications when users invoke this menu item to receive the timeline item ID. Retrieve the media from the timeline item in the payload property.<li>VOICE_CALL - Initiate a phone call using the timeline item's creator.phoneNumber attribute as recipient.<li>NAVIGATE - Navigate to the timeline item's location.<li>TOGGLE_PINNED - Toggle the isPinned state of the timeline item. <li>OPEN_URI - Open the payload of the menu item in the browser. <li>PLAY_VIDEO - Open the payload of the menu item in the Glass video player. <li>SEND_MESSAGE - Initiate sending a message to the timeline item's creator:If the creator.phoneNumber is set and Glass is connected to an Android phone, the message is an SMS.Otherwise, if the creator.email is set, the message is an email. 
     */
    public var action:              String                  = null;
    
    /**
     *A generic payload whose meaning changes depending on this MenuItem's action.
     <li>When the action is OPEN_URI, the payload is the URL of the website to view.
     <li>When the action is PLAY_VIDEO, the payload is the streaming URL of the video
     <li>When the action is GET_MEDIA_INPUT, the payload is the text transcription of a user's speech input 
     */
    public var payload:             String                  = null;
    
    /**
     * If set to true on a CUSTOM menu item, that item will be removed from the menu after it is selected. 
     */
    public var removeWhenSelected:  Boolean                 = false;
    
    
    /**
     * For CUSTOM items, a list of values controlling the appearance of the menu item in each of its states. A value for the DEFAULT state must be provided. If the PENDING or CONFIRMED states are missing, they will not be shown. 
     */
    public var values:              Vector.<MenuItemValues> = null;
    
    public function MenuItem()
    {
      values = new Vector.<MenuItemValues>();
    }
    
  }
  
}